### ISSUE TITLE
Devices sometimes lost when restarting Homebridge

### ISSUE THREAD

**Issue by caseypugh** [homebridge-simplisafe3/homebridge-simplisafe3#160]
### Describe The Bug:
I restarted Homebridge and received the following errors on bootup `ERR_INVALID_ARG_TYPE`:

<details><summary><b>VIEW LOGS</b></summary>
<p>

```sh
[12/5/2020, 2:31:37 PM] [Home Alarm] An error occurred while refreshing accessories: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at SS3Platform.refreshAccessories (/usr/lib/node_modules/homebridge-simplisafe3/index.js:157:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[12/5/2020, 2:31:37 PM] [Home Alarm] SimpliSafe login failed with error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at SS3Platform.refreshAccessories (/usr/lib/node_modules/homebridge-simplisafe3/index.js:157:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[12/5/2020, 2:31:37 PM] [Home Alarm] An error occurred while refreshing accessories: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at SS3Platform.refreshAccessories (/usr/lib/node_modules/homebridge-simplisafe3/index.js:157:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[12/5/2020, 2:31:37 PM] [Home Alarm] Initial accessories refresh failed with error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at SS3Platform.refreshAccessories (/usr/lib/node_modules/homebridge-simplisafe3/index.js:157:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

</p>
</details>

Afterward, all my SimpliSafe devices disappeared from Homebridge & Homekit. I tried restarting Homebridge again, and the error disappeared and all my devices showed back up as entirely new devices and lost all my automations/settings.

### To Reproduce:
Unfortunately, I'm unable to reproduce the behavior as it only happens occasionally on restart. It was operating fine for me for a while and only recently changed.

### Expected behavior:
I'd expect if there is a failed login attempt, it wouldnt automatically remove all devices, but would rather try to login again.

### Environment:

* **Plugin version**: 1.6.12
* **Node.js Version**:  v14.15.1
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Operating System**: Raspbian 

### Homebridge Config:
```json
       {
            "name": "Home Alarm",
            "auth": {
                "username": "**",
                "password": "**"
            },
            "cameras": false,
            "sensorRefresh": 30,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
```

**Comment by caseypugh** [comment]
I'm confused... I used the template?

**Comment by shamoon** [comment]
Hi @caseypugh yea the auto-closing thing can be a little aggressive, you can’t really edit the template or it’ll do that.

Anyway, as for this issue, never seen it before, do you have any sense for how to reproduce it or did it only happen once?

**Comment by caseypugh** [comment]
Ah yea I figured. Fiddled with the logs section a bit!

It has happened quite a few times to me on restart but not consistently.
Restarting again always brings the devices back. But not sure how to
recreate the problem for you.

Some ideas that might have triggered it:
- I have two homebridge instances running both with the same simplisafe
account set up. I do this for user access control reasons
- Also was working on another unrelated homebridge plugin and ran ‘sudo npm
link’ to test it. After restarting homebridge thats when i first saw the
simplisafe error but could have been a coincidence?

**Comment by shamoon** [comment]
Hmm, so one thing is you can try ticking the `persistAccessories` option to see if that prevents losing the accessories. But its an odd bug and Im not clear if its related to logging in or what. If you can provide more of the logs and with `debug` enabled (thats in the issue template 🙂) that might help.

**Comment by caseypugh** [comment]
Dang you got me 😢 I had actually ran it with debug mode on but didnt see
any extra Simplisafe logs besides the one I already shared with you. But
happy to try again... will report back if I find anything

**Comment by shamoon** [comment]
Ha. Make sure you enable debug `-D` for homebridge too, see https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#debug

**Comment by caseypugh** [comment]
Ah yea, totally missed the debug in simplisafe and the `persistAccessories` settings. I imagine the persist setting will fix my main problem, still dont know how to recreate the login error. It doesn't seem to be happening at all today.

IMHO, your devices shouldnt get removed when their is a login issue. Perhaps `persistAccessories` should default on? But I don't know if that would cause other issues.

**Comment by shamoon** [comment]
Agreed, but actually it shouldnt / doesnt. The error implies an issue getting the system serial number not really logging in, which again I've never seen before. Maybe logs will have a clue, thanks
