### ISSUE TITLE
Homebridge v1.3.0-beta.33

### ISSUE THREAD

**Issue by pattont** [homebridge-simplisafe3/homebridge-simplisafe3#167]
Testing the v1.3.0 version of HomeBridge and the Simplisafe plugin appears to be broken.

> at Bridge.Accessory.handleCharacteristicRead (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1196:24)
(node:1198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:1198) UnhandledPromiseRejectionWarning: Error: characteristic value expected number and received object
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1859:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1428:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SS3EntrySensor.getState (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/entrySensor.js:83:14)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/entrySensor.js:34:109)
    at Characteristic.emit (events.js:321:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1404:14
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1402:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:110:16)
    at Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:589:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1478:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:110:16)
    at Bridge.Accessory.handleCharacteristicRead (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1196:24)
>

**Comment by shamoon** [comment]
Hi @pattont, appreciate the report. I just released [v1.6.15](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/releases/tag/v1.6.15) that should hopefully address this. Please let us know how it goes

**Comment by pattont** [comment]
Awesome!! thank you so much!
