### ISSUE TITLE
Plug-in crashes Home bridge when trying to view camera feed

### ISSUE THREAD

**Issue by ronnyf** [homebridge-simplisafe3/homebridge-simplisafe3#171]
occurs 100% of the time

configured camera for rpi hw acceleration,
Restarted HB,
Opened feed, 
Switched source (got multiple cams setup)

[01/01/2021, 16:42:32] [Home Alarm] An error occurred while making snapshot request:  
[01/01/2021, 16:42:32] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:276:9
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-simplisafe3/node_modules/jpeg-extract/index.js:14:18)
    at Request.emit (node:events:376:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-simplisafe3/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:376:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
[01/01/2021, 16:42:32] Got SIGTERM, shutting down Homebridge...

**Comment by shamoon** [comment]
Hi @ronnyf Please include all of the requested info in the template. And I am not seeing this behavior, can you elaborate on "switched source"? Also would be helpful to have longer logs e.g. from a few seconds/minutes before the issue all the way through occurrence. If you provide I can take a look.

**Comment by ronnyf** [comment]
filed new bug:
https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/172
