### ISSUE TITLE
Homebridge won't load after install

### ISSUE THREAD

**Issue by johnlcoxjr** [homebridge-simplisafe3/homebridge-simplisafe3#185]
### Describe The Bug:

After installing the plugin and adding the config information, homebridge can't start

### To Reproduce:

Adding this line with correct username and password, it hangs.  Removing it, and homebridge loads.
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "auth": {
                "username": "XXX",
                "password": "XXX"
            }
        }

### Expected behavior:

Expected it to load

### Environment:

* **Plugin version**: 1.6.16
* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.1.7
* **Operating System**: Raspian

### Homebridge Config:

{
    "bridge": {
        "name": "Homebridge 8396",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51975,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "auth": {
                "username": "XXX",
                "password": "XXX"
            }
        }
    ]
}
```json
Paste the relevant section of your homebridge config.json here
```

### Logs:

[Link to logs]()
```
Paste Homebridge Logs here
```
[1/25/2021, 1:32:10 PM] Error loading platform requested in your config.json at position 1
[1/25/2021, 1:32:10 PM] Error: The requested plugin 'homebridge-simplisafe3' was not registered.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:235:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by shamoon** [comment]
Did you install the plugin? If so, how?

**Comment by johnlcoxjr** [comment]
npm install -g --unsafe-perm homebridge-simplisafe3


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shamoon** [comment]
Looks like youre running config ui x, have you tried installing through that? I dont see anything obvious in your config but uh, this plugin works so its got to just be an install issue...

**Comment by johnlcoxjr** [comment]
Do you mean, did I edit the json from the config page?  Yes.  Sorry if I'm stupid.  I ran the install as above, and added the config file manually.  One thing though, homebridge-simplisafe is not listed as a plugin???

**Comment by johnlcoxjr** [comment]
Okay.  I'm stupid.  Thank you

**Comment by shamoon** [comment]
Ha, no worries
