### ISSUE TITLE
Simplisafe Unable to Authenticate

### ISSUE THREAD

**Issue by jt70471** [homebridge-simplisafe3/homebridge-simplisafe3#255]
Hi, I've receiving the following error when the plugin tries to refresh the oauth2 token. The full debug log is attached...

[homebridge.log (1).txt](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/7470559/homebridge.log.1.txt)

I have tried to re-authenticate using the UI, however, it seems to never get past the point where I get the direct URL...

**Comment by jt70471** [comment]
Heh, I've looked everywhere and I can't find an issue template anywhere... Does anyone know what template I should be using to open an issue???

**Comment by shamoon** [comment]
Hey @jt70471   when you start a “Bug Request” issue it gives a template that has to be followed otherwise the bot gets angry. 

Anyway, as for your question, I think more info is needed (which is what the template is for 😁). Things like what OS, platform, version etc and can you describe the issue in more detail, perhaps with screenshots if needed? There are a lot of questions on here about this so searching may help, as well as reviewing the documentation.

LMK…

**Comment by jt70471** [comment]
Thanks, I went back to open a new issue and I see the options for bug report, etc… didn’t have those options for the first one I opened, no idea why.

Thanks for the reply. I’ll get one properly submitted tonight.

--
Jeff Thompson

**Comment by shamoon** [comment]
You can just copy and paste the template and put it here and I'll take a look, no need to make a new one =)

**Comment by jt70471** [comment]
### Describe The Bug:

Simplisafe authentication is failing due to http return code 403 when attempting to refresh the token. I have attached the full debug log, but here's the error from that log:

`
[11/3/2021, 3:34:32 PM] [Home Alarm] SimpliSafe login failed with error: Error: Error refreshing token: Error: Request failed with status code 403
    at SimpliSafe3AuthenticationManager.refreshCredentials (/homebridge/node_modules/homebridge-simplisafe3/common/authManager.js:212:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/3/2021, 3:34:32 PM] [Home Alarm] See the plugin README for more information on authenticating with SimpliSafe.
`
This may be a Simplisafe API issue, because when I attempt to re-authenticate via the homebridge settings UI, the authentication request is not returning the callback URL.

### To Reproduce:

1. Established login to Simplisafe via the settings UI initially, which worked successfully and the Simplisafe authentication worked as expected for weeks (if not months).
2. Using Apple IOS Home App, I see my Simplisafe Alarm System is not refreshing correctly.
3. Reviewed homebridge logs and see authentication error shown above while trying to renew the oath2 token.

### Expected behavior:

The plugin is expected to successfully renew/refresh the oath2 token and complete a successful authentication via the Simplisafe API.

### Environment:

* **Plugin version**: v1.8.4
* **Node.js Version**: v16.13.0
* **NPM Version**: v8.1.0
* **Homebridge Version**: v1.3.5
* **Operating System**: OS is Ubuntu 20.04 running docker 19.03.12 and homebridge running in an Alpine Linux 3.12 container

### Homebridge Config:



```json
{
            "name": "Home Alarm",
            "cameras": true,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "_bridge": {
                "username": "0E:A1:C7:D5:45:0C",
                "port": 49762
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
},
```

### Screenshots:


### Logs:





[Link to logs]()
```
[11/3/2021, 3:33:56 PM] [Homebridge UI] Homebridge log truncated by jefftee.
[11/3/2021, 3:34:00 PM] [Homebridge UI] Homebridge restart request received
[11/3/2021, 3:34:00 PM] [Homebridge UI] No restart command defined, killing process...
[11/3/2021, 3:34:00 PM] [HB Supervisor] Stopping services...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down Homebridge...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2021, 3:34:00 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2021, 3:34:05 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null


    Thank you for using the oznu/homebridge docker image!

  If you find this project useful please STAR it on GitHub:

         https://github.com/oznu/docker-homebridge

                Or donate to the project:

            https://github.com/sponsors/oznu
                  https://paypal.me/oznu

[11/3/2021, 3:34:13 PM] [HB Supervisor] OS: Linux 5.4.0-89-generic x64
[11/3/2021, 3:34:13 PM] [HB Supervisor] Node.js v16.13.0 /usr/local/bin/node
[11/3/2021, 3:34:13 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[11/3/2021, 3:34:13 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[11/3/2021, 3:34:24 PM] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on 0.0.0.0 port 8581
[11/3/2021, 3:34:25 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[11/3/2021, 3:34:25 PM] [HB Supervisor] Starting Homebridge with custom env: {"DEBUG":"1"}
[11/3/2021, 3:34:25 PM] [HB Supervisor] Started Homebridge v1.3.5 with PID: 6954
Initializing HAP-NodeJS v0.9.6...
[11/3/2021, 3:34:26 PM] Loaded config.json with 3 accessories and 3 platforms.
[11/3/2021, 3:34:26 PM] Loaded 0 cached accessories from cachedAccessories.
[11/3/2021, 3:34:26 PM] ---
[11/3/2021, 3:34:27 PM] Loaded plugin: homebridge-dummy@0.5.0
[11/3/2021, 3:34:27 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/3/2021, 3:34:27 PM] ---
[11/3/2021, 3:34:28 PM] Loaded plugin: homebridge-plex-webhooks@2.1.2
[11/3/2021, 3:34:28 PM] Registering platform 'homebridge-plex-webhooks.PlexWebhooks'
[11/3/2021, 3:34:28 PM] ---
[11/3/2021, 3:34:28 PM] Loaded plugin: homebridge-simplisafe3@1.8.4
[11/3/2021, 3:34:28 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
[11/3/2021, 3:34:28 PM] ---
[11/3/2021, 3:34:28 PM] Loaded plugin: homebridge-config-ui-x@4.41.2
[11/3/2021, 3:34:28 PM] Registering platform 'homebridge-config-ui-x.config'
[11/3/2021, 3:34:28 PM] ---
[11/3/2021, 3:34:28 PM] Loading 3 platforms...
[11/3/2021, 3:34:28 PM] [Config] Initializing config platform...
[11/3/2021, 3:34:28 PM] [Config] Running in Service Mode
[11/3/2021, 3:34:28 PM] [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[11/3/2021, 3:34:28 PM] [Home Alarm] Initializing child bridge 0E:A1:C7:D5:45:0C
[11/3/2021, 3:34:28 PM] [Plex Webhooks Platform] Initializing PlexWebhooks platform...
[11/3/2021, 3:34:28 PM] [Plex Webhooks Platform] Initializing child bridge 0E:57:7B:D5:BA:55
[11/3/2021, 3:34:28 PM] Loading 3 accessories...
[11/3/2021, 3:34:28 PM] [Away Switch] Initializing DummySwitch accessory...
[11/3/2021, 3:34:28 PM] [Away Switch] Initializing child bridge 0E:AB:EB:E4:9D:73
[11/3/2021, 3:34:28 PM] [Night Switch] Initializing DummySwitch accessory...
[11/3/2021, 3:34:28 PM] [Night Switch] Initializing child bridge 0E:47:00:BE:6C:B3
[11/3/2021, 3:34:28 PM] [Page Switch] Initializing DummySwitch accessory...
[11/3/2021, 3:34:28 PM] [Page Switch] Initializing child bridge 0E:2E:8A:5C:F1:FF
Preparing Advertiser for 'Homebridge 6376 F8C3' using bonjour-hap backend!
Setup Payload:
X-HM://0023Y4JJZ43HV
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 288-79-359 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 6376 F8C3' using bonjour-hap backend!
[11/3/2021, 3:34:29 PM] Homebridge v1.3.5 (Homebridge 6376) is running on port 53758.
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
[11/3/2021, 3:34:29 PM] [Away Switch] Launched child bridge with PID 7065
[11/3/2021, 3:34:29 PM] [Plex Webhooks Platform] Launched child bridge with PID 7059
[11/3/2021, 3:34:29 PM] [Home Alarm] Launched child bridge with PID 7058
[11/3/2021, 3:34:29 PM] [Page Switch] Launched child bridge with PID 7077
[11/3/2021, 3:34:30 PM] [Night Switch] Launched child bridge with PID 7071
[11/3/2021, 3:34:29 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/3/2021, 3:34:30 PM] [Away Switch] Loaded homebridge-dummy v0.5.0 child bridge successfully
[11/3/2021, 3:34:30 PM] Loaded 0 cached accessories from cachedAccessories.0EABEBE49D73.
[11/3/2021, 3:34:30 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/3/2021, 3:34:30 PM] [Page Switch] Loaded homebridge-dummy v0.5.0 child bridge successfully
[11/3/2021, 3:34:30 PM] Loaded 0 cached accessories from cachedAccessories.0E2E8A5CF1FF.
[11/3/2021, 3:34:30 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/3/2021, 3:34:30 PM] [Night Switch] Loaded homebridge-dummy v0.5.0 child bridge successfully
[11/3/2021, 3:34:30 PM] [Away Switch] Setting switch to false
[11/3/2021, 3:34:30 PM] Loaded 0 cached accessories from cachedAccessories.0E4700BE6CB3.
Preparing Advertiser for 'Away Switch 1B40' using bonjour-hap backend!
Starting to advertise 'Away Switch 1B40' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] [Night Switch] Setting switch to false
Preparing Advertiser for 'Page Switch D533' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] Homebridge v1.3.5 (Away Switch) is running on port 33836.
Starting to advertise 'Page Switch D533' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] Homebridge v1.3.5 (Page Switch) is running on port 35429.
Preparing Advertiser for 'Night Switch CFC8' using bonjour-hap backend!
Starting to advertise 'Night Switch CFC8' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] Homebridge v1.3.5 (Night Switch) is running on port 31858.
[11/3/2021, 3:34:30 PM] Registering platform 'homebridge-plex-webhooks.PlexWebhooks'
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] Loaded homebridge-plex-webhooks v2.1.2 child bridge successfully
[11/3/2021, 3:34:30 PM] Loaded 2 cached accessories from cachedAccessories.0E577BD5BA55.
Preparing Advertiser for 'Plex Webhooks Platform 648B' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] Found 2 accessories in config:
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] • Family Room Plex
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] • Bedroom Plex
[11/3/2021, 3:34:30 PM] [homebridge-plex-webhooks] This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received object. See https://git.io/JtMGR for more info.
[11/3/2021, 3:34:30 PM] [homebridge-plex-webhooks] Error: 
    at Manufacturer.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Manufacturer.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2022:16)
    at Manufacturer.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1334:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:475:35)
    at new PlexWebhooksPlatformAccessory (/homebridge/node_modules/homebridge-plex-webhooks/lib/accessory.js:23:8)
    at /homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:106:29
    at Array.map (<anonymous>)
    at PlexWebhooksPlatform._updateAccessories (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:104:8)
    at PlexWebhooksPlatform._discoverAccessories (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:52:10)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:31:12)
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] Updating accessory [Family Room Plex] (92579901-3b8a-48a0-b9d5-bd6b6cd70184)
[11/3/2021, 3:34:30 PM] [homebridge-plex-webhooks] This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received object. See https://git.io/JtMGR for more info.
[11/3/2021, 3:34:30 PM] [homebridge-plex-webhooks] Error: 
    at Manufacturer.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Manufacturer.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2022:16)
    at Manufacturer.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1334:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:475:35)
    at new PlexWebhooksPlatformAccessory (/homebridge/node_modules/homebridge-plex-webhooks/lib/accessory.js:23:8)
    at /homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:106:29
    at Array.map (<anonymous>)
    at PlexWebhooksPlatform._updateAccessories (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:104:8)
    at PlexWebhooksPlatform._discoverAccessories (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:52:10)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-plex-webhooks/lib/platform.js:31:12)
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] Updating accessory [Bedroom Plex] (899dd509-9dac-400a-8137-b7b2ca291678)
[11/3/2021, 3:34:30 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
[11/3/2021, 3:34:30 PM] [Home Alarm] Loaded homebridge-simplisafe3 v1.8.4 child bridge successfully
Starting to advertise 'Plex Webhooks Platform 648B' using bonjour-hap backend!
[11/3/2021, 3:34:30 PM] Homebridge v1.3.5 (Plex Webhooks Platform) is running on port 53297.
[11/3/2021, 3:34:30 PM] [Plex Webhooks Platform] Server is listening at http://192.168.4.31:32401
[11/3/2021, 3:34:30 PM] Loaded 11 cached accessories from cachedAccessories.0EA1C7D5450C.
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'SimpliSafe 3' (uuid 639ba835-ebb4-446c-bd43-4fe853bf02d2)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Office' (uuid db3c8b3e-2d96-481e-98e3-8d4569fe042b)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Kitchen' (uuid 65fc889d-619c-43b0-b2de-fd2ece1c2ac3)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Waterheater' (uuid ede0e082-68e6-44fd-9c1c-776c942fcbc1)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Back Door' (uuid 39e8c591-fb99-45cc-a600-328ce4a46fcf)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Front Door' (uuid 8d3633f0-3ed7-4727-973c-07dab4c4a5e7)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Gameroom' (uuid b97823de-6b44-4ad4-bad2-72a37b572cdc)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Garage' (uuid 92b1f812-2ead-458b-8665-6d01e5eebf66)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Sunroom' (uuid df488abf-7693-4858-a996-ca833fb59fc9)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Front Door' (uuid fccf6e17-fcb4-4322-999b-6f9d37da5a1d)
[11/3/2021, 3:34:31 PM] [Home Alarm] Configure existing accessory 'Front Door' (uuid 07e0e44a-c28c-41f0-8e2e-5d6b04dcf14a)
Preparing Advertiser for 'Home Alarm 1733' using bonjour-hap backend!
[11/3/2021, 3:34:31 PM] [Home Alarm] Found 11 cached accessories being configured
Starting to advertise 'Home Alarm 1733' using bonjour-hap backend!
[11/3/2021, 3:34:31 PM] Homebridge v1.3.5 (Home Alarm) is running on port 49762.
[11/3/2021, 3:34:32 PM] [Home Alarm] SimpliSafe login failed with error: Error: Error refreshing token: Error: Request failed with status code 403
    at SimpliSafe3AuthenticationManager.refreshCredentials (/homebridge/node_modules/homebridge-simplisafe3/common/authManager.js:212:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/3/2021, 3:34:32 PM] [Home Alarm] See the plugin README for more information on authenticating with SimpliSafe.
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 639ba835-ebb4-446c-bd43-4fe853bf02d2
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found db3c8b3e-2d96-481e-98e3-8d4569fe042b
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 65fc889d-619c-43b0-b2de-fd2ece1c2ac3
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found ede0e082-68e6-44fd-9c1c-776c942fcbc1
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 39e8c591-fb99-45cc-a600-328ce4a46fcf
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 8d3633f0-3ed7-4727-973c-07dab4c4a5e7
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found b97823de-6b44-4ad4-bad2-72a37b572cdc
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 92b1f812-2ead-458b-8665-6d01e5eebf66
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found df488abf-7693-4858-a996-ca833fb59fc9
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found fccf6e17-fcb4-4322-999b-6f9d37da5a1d
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Device not found 07e0e44a-c28c-41f0-8e2e-5d6b04dcf14a
[11/3/2021, 3:34:32 PM] [Home Alarm] Remove accessory
[11/3/2021, 3:34:32 PM] [Home Alarm] Initial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /homebridge/node_modules/homebridge-simplisafe3/index.js:103:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by shamoon** [comment]
A couple things to clarify:

- (I think the answer to this is yes, but just checking) There is a completely new process for authenticating, as the logs mention, have you ever gotten through that process successfully yet? (its only been live for a few weeks) Have you tried the command line option as well? See https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#simplisafe-authentication
- Can you be more specific about what happens when you try to authenticate via HB UI? You said "it doesnt give the callback URL", exactly what does happen? And note that you have be on a desktop device and the process is slightly different in Chrome vs Safari (again, see README)
- I have found that the new auth is pretty stable but every once-in-a-while the token does seem to get invalidated and requires manually re-authenticating, but hopefully its not a frequent thing for most folks

**Comment by jt70471** [comment]
Hi, yes, when I last upgraded the plugin, the authentication worked fine via the Homebridge UI. It seems that the issue started when the oauth2 token had to be renewed or refreshed.

I just successfully re-authenticated and looks like things are working ok again. I had to go to the developer tools console and copy/paste the url from the console to the homebridge UI and after restarting homebridge, looks like I'm back in business.

You can close this as the manual re-authentication was successful. Should it occur again I'll report again with new logs, etc.

Thanks for your help and quick responses!

**Comment by shamoon** [comment]
Cool. Yea the process isn’t as seamless as I wish but it’s obviously not designed to work with Homebridge so we’re forced to make it work. In particular the console thing is not obvious.

the plug-in is refreshing the token all the time, every hour to be specific. Theoretically you shouldn’t have to ever intervene but yea, it’s happened to me on occasion as well.

Anyway, glad it’s sorted for now.

**Comment by joemckie** [comment]
I thought I'd drop a note to anyone having this issue in the future:

If you need to reauthenticate, opening the SimpliSafe auth page in a new tab doesn't make the input appear, it has to be left clicked 🤷‍♂️

**Comment by fancypantsifier** [comment]
I bumped into this today too and it was a bit painful because it meant that my arrival home caused my alarm to go off because my HomeKit automation to disable the alarm based on my presence and the garage door opening did not work since nothing triggering off my Simplisafe sensors was working. It caught by surprise and I'm just glad it was me and not my wife since we've come to trust the automations offered by this awesome plugin. 

Is there a way we could get some kind of signal or notification when the plugin needs manual reauthentication (e.g. starts repeatedly receiving this 403 error)? I also use the the dummy switch and messenger plugins for HomeBridge, so something that would allow me to flip a virtual switch that triggers an IFFFT notification would be totally acceptable. I'm happy to open a feature request if this is remotely feasible. Thanks!
