### ISSUE TITLE
"Error retrieving token" in new authentication

### ISSUE THREAD

**Issue by abraver** [homebridge-simplisafe3/homebridge-simplisafe3#269]
### Describe The Bug:

I've been trying to set up the new authentication, but have run into an issue—both via ConfigUI and via `homebridge-simplisafe3 login`.

With ConfigUI, I can click "launch simplisafe login", log in on the simplisafe site, and get the com.SimpliSafe.mobile:// address.  When I paste that address into the "redirected URL field", an error pops up saying "Error retrieving token.  Please try again."

Via the command line, I can get the com.SimpliSafe.mobile:// address as with Config UI, but when I enter it, I get the following error:

``
An error occurred retrieving credentials:
Error: Error getting token: Error: Request failed with status code 403
    at SimpliSafe3AuthenticationManager.getToken (/usr/local/lib/node_modules/homebridge-simplisafe3/common/authManager.js:189:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Login.run (/usr/local/lib/node_modules/homebridge-simplisafe3/commands/login.js:58:7)
    at async Login._run (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@oclif/command/lib/command.js:43:20)
``

### To Reproduce:

Via ConfigUI: click "settings" on the Homebridge Simplisafe 3 plugin box on the plugins page.  Get redirect URL via "launch simplisafe login", then paste the redirected URL into the appropriate box.

Via command line: run `homebridge-simplisafe3 login`, get redirect URL, paste URL into command line.

### Expected behavior:

Homebridge recognizes the redirect URL

### Environment:

* **Plugin version**:  homebridge-simplisafe3@1.8.8
* **Node.js Version**:  v16.13.1
* **NPM Version**:  8.1.2
* **Homebridge Version**:  
* **Operating System**: 

### Homebridge Config:

```json
{
    "name": "Home Alarm",
    "cameras": false,
    "sensorRefresh": 15,
    "persistAccessories": false,
    "resetSimpliSafeId": false,
    "cameraOptions": {
        "enableHwaccelRpi": false
    },
    "platform": "homebridge-simplisafe3.SimpliSafe 3"
}
```

### Screenshots:

Not applicable

### Logs:

[Link to logs]()
```
[23/12/2021, 13:49:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getAuthCodeFromUrl
[23/12/2021, 13:49:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getToken
[23/12/2021, 13:49:34] [Homebridge UI] [homebridge-simplisafe3] Error: Error getting token: Error: Request failed with status code 403
    at SimpliSafe3AuthenticationManager.getToken (/usr/local/lib/node_modules/homebridge-simplisafe3/common/authManager.js:189:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UiServer.getToken (/usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:65:11)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[23/12/2021, 13:51:02] [Homebridge UI] [homebridge-simplisafe3] Terminating child process...
[23/12/2021, 13:51:02] [Homebridge UI] [homebridge-simplisafe3] Child process ended
```

**Comment by shamoon** [comment]
Hey @abraver seems like the plug-in is having trouble actually using the credentials you’re getting. Are you setting this up for the first time or was it working before? You definitely have a monitoring plan etc?

**Comment by abraver** [comment]
I tried again, disabling all Safari extensions, and it worked.  I guess it was just one of my extensions doing something weird...
