### ISSUE TITLE
SIGTERM shortly after "SimpliSafe real time events disconnected."

### ISSUE THREAD

**Issue by lmcquade** [homebridge-simplisafe3/homebridge-simplisafe3#317]
### Describe The Bug:
Less than a minute after seeing "SimpliSafe real time events disconnected." in the log, I see a "Error: WebSocket was closed before the connection was established", which sends a SIGTERM to Homebridge, causing it to restart.

### To Reproduce:
Appears to happen "SimpliSafe real time events disconnected."  Happens periodically on its own.

### Expected behavior:
Don't crash and cause Homebridge to restart :)

### Environment:
* **Plugin version**: homebridge-simplisafe3@1.9.9
* **Node.js Version**: v17.6.0
* **NPM Version**: 8.5.3
* **Homebridge Version**: 1.4.0
* **Operating System**: macOS

### Homebridge Config:
```json
{
    "name": "Home Alarm",
    "cameras": false,
    "debug": false,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "resetSimpliSafeId": false,
    "cameraOptions": {
        "enableHwaccelRpi": false
    },
    "platform": "homebridge-simplisafe3.SimpliSafe 3"
}
```

### Screenshots:
not applicable

### Logs:
```
[3/7/2022, 8:51:53 AM] [Home Alarm] SimpliSafe real time events disconnected.
[3/7/2022, 8:52:26 AM] Error: WebSocket was closed before the connection was established
    at WebSocket.terminate (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/websocket.js:479:14)
    at SimpliSafe3.handleSocketConnectionFailure (/usr/local/lib/node_modules/homebridge-simplisafe3/simplisafe.js:640:17)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/simplisafe.js:462:12)
    at WebSocket.emit (node:events:527:28)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/websocket.js:851:27)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[3/7/2022, 8:52:26 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by shamoon** [comment]
Hi @lmcquade just to clarify, does this happen every time there's a "disconnected" event? Yes, those disconnections are sorta random (not something we can control) but in my testing I have not seen this specific issue and it will re-connect after disconnects. Does it sometimes (usually?) reconnect or do you see this every time?

A fix for this should be straightforward but LMK. Thanks

**Comment by lmcquade** [comment]
Hi @shamoon, no it is not 100%.   In my logs, I see 33 "SimpliSafe real time events disconnected.", 9 of which were followed by a "Error: WebSocket was closed before the connection was established" error.

**Comment by shamoon** [comment]
1. Thats good to know, I think a fix for this should be simple I just want to test a little.
2. That's a lot of disconnects! I have _maybe_ 2-3 of those per day, usually. Again its not something this plugin can really control but I am curious why so many. You dont have general connectivity issues? Is your Homebridge machine hardwired?

Thanks again for reporting, fix will be in the next release soon.

**Comment by shamoon** [comment]
Actually, one more thing. Can you include more of your logs before the example you posted, like the couple minutes before and up through the error. Thanks

**Comment by lmcquade** [comment]
Those 33 are from the last 4 days - so like 8/day on avg.  In general connectivity is fine.  Homebridge machine is hardwired.

I've enabled Debug, and will send you more detailed logs if it happens again.

**Comment by mherrema** [comment]
I'm also experiencing this scenario, only over the last day or two. I just enabled debug as well so can report back with additional context if it's helpful.

**Comment by shamoon** [comment]
Hey guys, this should be fixed in 1.9.10. Im fairly confident crash wont happen but the one thing thats hard to test is how the plugin recovers after those errors but in my testing this works well. Let me know!

**Comment by lmcquade** [comment]
Pulling it down now, and will continue to run it in Debug for a few days.

**Comment by lmcquade** [comment]
@shamoon, Homebridge hasn't crashed since your fix, but I did notice this interaction this morning:
```
[3/9/2022, 11:11:55 AM] [Home Alarm] SSAPI socket `heartbeat`
[3/9/2022, 11:12:55 AM] [Home Alarm] SSAPI socket `heartbeat`
[3/9/2022, 11:13:56 AM] [Home Alarm] SSAPI socket `error`: RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/receiver.js:189:14)
    at Receiver.startLoop (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/receiver.js:136:22)
    at Receiver._write (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at Receiver.Writable.write (node:internal/streams/writable:335:10)
    at TLSSocket.socketOnData (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/websocket.js:1231:35)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
[3/9/2022, 11:13:56 AM] [Home Alarm] SimpliSafe real time events disconnected.
[3/9/2022, 11:13:56 AM] [Home Alarm] SSAPI socket connection lost. Next attempt will be in 1s.
[3/9/2022, 11:14:03 AM] [Home Alarm] SSAPI socket `error`: Error: Opening handshake has timed out
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/ws/lib/websocket.js:812:7)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:758:9)
    at Object.onceWrapper (node:events:641:28)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.Socket._onTimeout (node:net:502:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[3/9/2022, 11:14:03 AM] [Home Alarm] SimpliSafe real time events disconnected.
[3/9/2022, 11:14:03 AM] [Home Alarm] SSAPI socket connection lost. Next attempt will be in 2s.
[3/9/2022, 11:14:06 AM] [Home Alarm] SSAPI socket `open`
[3/9/2022, 11:14:06 AM] [Home Alarm] SSAPI socket `hello`
[3/9/2022, 11:14:06 AM] [Home Alarm] SSAPI socket `registered`
[3/9/2022, 11:14:06 AM] [Home Alarm] SSAPI socket `subscribed`
[3/9/2022, 11:14:06 AM] [Home Alarm] SimpliSafe real time events connected.
[3/9/2022, 11:14:21 AM] [Home Alarm] Preemptively authenticating with SimpliSafe
[3/9/2022, 11:14:22 AM] [Home Alarm] SimpliSafe credentials refresh was successful
[3/9/2022, 11:15:06 AM] [Home Alarm] SSAPI socket `heartbeat`
[3/9/2022, 11:16:06 AM] [Home Alarm] SSAPI socket `heartbeat`
```

**Comment by shamoon** [comment]
> @shamoon, Homebridge hasn't crashed since your fix, but I did notice this interaction this morning:

Thanks for the update, thats great! Yea that code actually all looks OK, the first part is a typical error. The second part is because I was forced to add a timeout on re-connecting. I have no way to know exactly the right limit to use for that (not like its documented anywhere =) so I tested a few durations and settled on one that works. It may be the case that it should be longer (or shorter). 

But still looks like its working appropriately, catches the timeout error and just tries again.

As long as you dont see the timeout error very frequently it should be OK. Not expecting you to keep `debug` on forever (noisy, eh?!) but lmk if you do notice the above. Thanks again
