### ISSUE TITLE
Simplisafe3 will not link account

### ISSUE THREAD

**Issue by GOTDNRV** [homebridge-simplisafe3/homebridge-simplisafe3#336]
### Description

After loading the plug-in and selecting the link account tab, the system states the password is incorrect when inputting an ID and PW.  If you change the password, it still defaults to an incorrect password.

### Expected behavior

After inputting the ID and Password to link the account.

### Steps to reproduce

install the plug in and try to link an account.

### Homebridge logs

```bash
4/18/2022, 10:24:57 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSimpliSafe login failed with error: Error: No authentication credentials detected.
    at SimpliSafe3AuthenticationManager.refreshCredentials (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/lib/authManager.js:193:13)
    at new SS3Platform (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:82:41)
    at /usr/src/bridge/server.ts:455:46
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/src/bridge/server.ts:438:31)
    at Server.start (/usr/src/bridge/server.ts:239:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Homebridge config.json contents

```json
4/18/2022, 10:24:57 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSee the plugin README for more information on authenticating with SimpliSafe.
Tried and still failed to link account
```

### Plugin version

1.10.3

### Homebridge version

4.2.1

### Node.js version

16.14.2

### Host OS

macOS

**Comment by shamoon** [comment]
Are you on HOOBS?

**Comment by shamoon** [comment]
HOOBS is not directly supported by this plugin, they simply claim so and patch support themselves. You can reach out to HOOBS directly or you can always switch to Homebridge =)
