### ISSUE TITLE
[BUG] A description of the issue

### ISSUE THREAD

**Issue by gagz135** [homebridge-simplisafe3/homebridge-simplisafe3#337]
### Description

For the last year, I’ve had a HomeKit automation (through HOOBS) set to arm SimpliSafe to Home mode every night at midnight. 

A few weeks ago, I noticed that this no longer happens, and that the SimpliSafe HomeKit tile is stuck in “Arming.” I’ve uninstalled and reinstalled the bridge/plug-in multiple times. No luck. 

### Expected behavior

The automation triggers SimpliSafe to arm to Home mode. 

### Steps to reproduce

Set automation to arm to Home mode.  
Set time to trigger automation. 
Run automation. 

### Homebridge logs

```bash
simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/17/2022, 11:50:33 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/17/2022, 11:50:34 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/17/2022, 8:55:20 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/17/2022, 8:55:21 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/17/2022, 8:59:42 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/17/2022, 8:59:43 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/17/2022, 9:46:26 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/17/2022, 9:46:27 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/18/2022, 12:00:00 AMmyQ BridgeERROR[myQ Bridge 3EDF@Garage Door@Garage Door@Target Door State] SET handler returned write response value, though the characteristic doesn't support write response
4/18/2022, 6:47:42 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/18/2022, 6:47:43 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/18/2022, 7:53:12 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/18/2022, 7:53:14 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/18/2022, 4:43:22 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3WARNINGSimpliSafe real time events disconnected.
4/18/2022, 4:43:23 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/18/2022, 5:09:50 PMmyQ BridgemyQERRORmyQ API: Connection has been reset.
4/18/2022, 5:09:50 PMmyQ BridgemyQERRORmyQ API: Unable to retrieve account information.
4/18/2022, 5:09:55 PMmyQ BridgemyQmyQ API: Successfully connected to the myQ API.
4/18/2022, 5:09:55 PMmyQ BridgemyQERRORmyQ API: Connection has been reset.
4/18/2022, 5:09:55 PMmyQ BridgemyQERRORmyQ API: Unable to retrieve account information.
4/18/2022, 5:11:56 PMmyQ BridgemyQmyQ API: Successfully connected to the myQ API.
4/18/2022, 5:19:29 PMmyQ BridgemyQERRORmyQ API: Connection has been reset.
4/18/2022, 5:19:29 PMmyQ BridgemyQERRORmyQ API: Unable to retrieve account information.
4/18/2022, 5:19:33 PMmyQ BridgemyQmyQ API: Successfully connected to the myQ API.
4/18/2022, 9:55:24 PMSimplisafe3 BridgeConfiguration change
4/18/2022, 9:55:24 PMsimplisafe3bridge stopping
4/18/2022, 9:55:29 PMSimplisafe3 Bridge starting
4/18/2022, 9:55:36 PMSimplisafe3 BridgeLoaded plugin 'homebridge-simplisafe3'
4/18/2022, 9:55:36 PMSimplisafe3 BridgeLoading 1 platforms...
4/18/2022, 9:55:36 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Specifying account number: 000434!B
4/18/2022, 9:55:36 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Found 18 cached accessories to be configured.
4/18/2022, 9:55:36 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Attempting intial SimpliSafe credentials refresh.
4/18/2022, 9:55:37 PMSimplisafe3 BridgeBridge is running on port 51846.
4/18/2022, 9:55:37 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe credentials refresh was successful
4/18/2022, 9:55:37 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Discovering devices from SimpliSafe
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORAn error occurred while refreshing accessories: Error: No matching monitoring plans found. Check your account and ensure you have an active plan. at SimpliSafe3.getSubscription (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/simplisafe.js:294:15) at processTicksAndRejections (node:internal/process/task_queues:96:5) at SS3Platform.discoverSimpliSafeDevices (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:176:26)
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSimpliSafe login failed with error: Error: No matching monitoring plans found. Check your account and ensure you have an active plan. at SimpliSafe3.getSubscription (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/simplisafe.js:294:15) at processTicksAndRejections (node:internal/process/task_queues:96:5) at SS3Platform.discoverSimpliSafeDevices (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:176:26)
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSee the plugin README for more information on authenticating with SimpliSafe.
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {635117a6-0b85-4d5a-aba6-2742140dce27} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {42777383-1dc9-4edb-81ea-07fed1c2ced3} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {77b52e58-bc0a-43f7-a4c7-84214ff3645f} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {d4f32450-619c-4cfe-bf4c-c47be05dfd92} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {b0ed2761-4397-495f-aabe-7fc4db70658f} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {49b39d09-c3ce-42b2-a10c-142d01211173} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {d30307af-fe1e-41da-abd1-e787b60c8e43} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {12007041-5634-4d30-a3d8-ec2eefb34649} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {161bcf3a-5674-4c28-a843-45655eef0344} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {ea51d470-8050-4462-b98f-dc4ea59a5c97} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {1228dc03-11f1-4a55-a934-ccdf6a138eac} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {9428fb43-d6b9-4c06-9a9c-b688633e4963} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {4dd12c5b-c330-40db-b531-8b4294f62a50} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {2e8efe3b-9571-4f21-a0ab-8bb3d7808c74} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {48f0f676-385e-45bb-be98-43a1fcf7e94e} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {9fba3c88-6151-4468-b176-236aeda1e6b5} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {18c78b3a-4623-43bb-81da-ba19429b8b91} not matched to a SimpliSafe device
4/18/2022, 9:55:40 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3Cached accessory {622394a0-a524-4c82-9375-078f5727ac68} not matched to a SimpliSafe device
4/18/2022, 9:55:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `open`
4/18/2022, 9:55:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `hello`
4/18/2022, 9:55:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `registered`
4/18/2022, 9:55:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `subscribed`
4/18/2022, 9:55:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SimpliSafe real time events connected.
4/18/2022, 9:56:44 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `heartbeat`
4/18/2022, 9:57:47 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `heartbeat`
4/18/2022, 9:58:50 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `heartbeat`
4/18/2022, 9:59:53 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3SSAPI socket `heartbeat`
```

### Homebridge config.json contents

```json
?
```

### Screenshots

![13130101-40E1-4C46-9F62-7F47D03E6924](https://user-images.githubusercontent.com/89422861/163905466-a64fabd8-90e2-4011-8a15-96cf3f1bd443.jpeg)

### Plugin version

1.10.3

### Homebridge version

1.4.0

### Node.js version

16.14.2

### Host OS

Raspbian

**Comment by shamoon** [comment]
Hi, unfortunately HOOBS is not directly supported by this plugin, they simply claim it is and patch support themselves. You can reach out to HOOBS directly or you can always switch to Homebridge =)

I would guess they need to update after recent changes to the plugin.

**Comment by docpowell** [comment]
I had the same issue with hoobs. Had to rereflash my sd card and reinstall hoobs onto it.

**Comment by gagz135** [comment]
Thank you @docpowell ! This solved it!

**Comment by docpowell** [comment]
You’re welcome. Glad it worked.
