### ISSUE TITLE
Cameras not streaming in the Home app

### ISSUE THREAD

**Issue by ColeB117** [homebridge-simplisafe3/homebridge-simplisafe3#346]
### Description

When I attempt to view a supported camera through the Home app, I get the error message "No Response - This Camera is not responding" on the app.

I receive the following information from Homebridge:

Unable to spawn ffmpeg process at undefined with error: TypeError: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at normalizeSpawnArguments (node:child_process:505:3)
    at spawn (node:child_process:693:13)
    at StreamingDelegate.handleStreamRequest (C:\Users\coleb\AppData\Roaming\npm\node_modules\homebridge-simplisafe3\lib\streamingDelegate.js:372:48) {
  code: 'ERR_INVALID_ARG_TYPE'

I understand this is an issue with ffmpeg. I installed the plugin via Homebridge Config UI X, but for some reason ffmpeg did not automatically install. I have attempted to install [ffmpeg for Homebridge](url) manually by running the .exe per their install instructions, but this didn't make any difference. I am using Homebridge on Windows 10 at the moment. I know others have submitted similar issues, but they seemed to figure it out on their own and I can't.

### Expected behavior

I expect to see a live stream of the camera.

### Steps to reproduce

1. Open the Home app.
2. Click on any Simplisafe camera.

### Homebridge logs

```bash
Unable to spawn ffmpeg process at undefined with error: TypeError: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at normalizeSpawnArguments (node:child_process:505:3)
    at spawn (node:child_process:693:13)
    at StreamingDelegate.handleStreamRequest (C:\Users\coleb\AppData\Roaming\npm\node_modules\homebridge-simplisafe3\lib\streamingDelegate.js:372:48) {
  code: 'ERR_INVALID_ARG_TYPE'
```

### Homebridge config.json contents

```json
"name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
```

### Plugin version

1.10.6

### Homebridge version

1.5.0

### Node.js version

16.15

### Host OS

Windows

**Comment by ColeB117** [comment]
No worries! Thank you for giving me some other leads.
