### ISSUE TITLE
[BUG] Reverted auth URL includes URLs and not functioning

### ISSUE THREAD

**Issue by cameronpcook** [homebridge-simplisafe3/homebridge-simplisafe3#353]
### Description

When going through the authentication flow—after upgrading to revert back to the URL-based method—the URL target on the button has spaces included in it: after "scope=offline_access"

https://auth.simplisafe.com/authorize?client_id=XXX&scope=offline_access**%20**email**%20**openid**%20**https://api.simplisafe.com/scopes/user:platform&response_type=code&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&code_challenge_method=S256&code_challenge=XXX&audience=https://api.simplisafe.com/&auth0Client=XXX

### Expected behavior

The URL should be a valid URL that can resolve on Simplisafe

### Steps to reproduce

1. Go to plugin settings
2. Click on "Show Authentication Settings"
3. Click "Launch Simplisafe Login"
4. Erroneous URL

### Homebridge logs

```bash
[Home Alarm] SimpliSafe login failed with error: {
  message: 'Request failed with status code 400',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: Request failed with status code 400\n' +
    '    at createError (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at settle (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/axios/lib/adapters/http.js:322:11)\n' +
    '    at IncomingMessage.emit (node:events:539:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1345:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Host: 'auth.simplisafe.com',
      'Content-Length': 186,
      'Auth0-Client': 'eyJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsiaU9TIjoiMTUuMCIsInN3aWZ0IjoiNS54In0sInZlcnNpb24iOiIxLjMzLjAifQ',
      'User-Agent': 'axios/0.26.1'
    },
    baseURL: 'https://auth.simplisafe.com/oauth',
    method: 'post',
    url: '/token',
    data: '{"grant_type":"refresh_token","client_id":"42aBZ5lYrVW12jfOuu3CQROitwxg9sN5","refresh_token":"v1.MTIyMlIe_tBcvOaNXkZYbMVnSOAlMDar2b0dl6X6wiZhQCPqjVku4aXNjqQPGyVDg3h48VFK_mvkX5EE2Gg9D7A1xjI"}',
    'axios-retry': { retryCount: 0, lastRequestTime: 1658613380921 }
  },
  code: undefined,
  status: 400
}
[23/07/2022, 14:56:21] [Home Alarm] See the plugin README for more information on authenticating with SimpliSafe.
[23/07/2022, 14:56:21] [Home Alarm] Initial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /usr/local/lib/node_modules/homebridge-simplisafe3/index.js:101:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Homebridge config.json contents

```json
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Home Alarm",
            "cameras": false,
            "debug": true,
            "sensorRefresh": 60,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
```

### Plugin version

1.10.7 

### Homebridge version

1.5.0

### Node.js version

16.15.1

### Host OS

Raspbian

**Comment by cameronpcook** [comment]
Disregard; local issue
