### ISSUE TITLE
[BUG] Cannot configure plugin, [homebridge-simplisafe3] undefined:1   SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by cattastrophe0** [homebridge-simplisafe3/homebridge-simplisafe3#372]
### Description

I've removed and readied the plugin several times. Any time I try to use the Homebridge UI to re-setup the plugin, the following error occurs:

```
[12/7/2022, 10:41:54 PM] [Homebridge UI] [homebridge-simplisafe3] undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SimpliSafe3AuthenticationManager.parseAccountsFile (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:123:28)
    at new SimpliSafe3AuthenticationManager (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:84:10)
    at new UiServer (/usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:12:28)
    at /usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:79:12
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:80:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[12/7/2022, 10:41:54 PM] [Homebridge UI] [homebridge-simplisafe3] Child process ended
```

I've tried reverting to an older version of the plugin, clearing cached accessories, and checked the config.json manually and can't see any sign of syntax errors or even that the bridge is setup at all. I also tried to manually configure the JSON and got the same error.

### Expected behavior

The plugin should be able to be setup.

### Steps to reproduce

see above

### Homebridge logs

```bash
[12/7/2022, 10:53:27 PM] [Homebridge UI] [homebridge-simplisafe3] undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SimpliSafe3AuthenticationManager.parseAccountsFile (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:123:28)
    at new SimpliSafe3AuthenticationManager (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:84:10)
    at new UiServer (/usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:12:28)
    at /usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:79:12
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:80:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[12/7/2022, 10:53:27 PM] [Homebridge UI] [homebridge-simplisafe3] Child process ended
[12/7/2022, 10:53:33 PM] [Homebridge UI] [homebridge-simplisafe3] Terminating child process...
```

### Homebridge config.json contents

```json
no changes to config.json have been made by this plugin yet. added

{
    "platform": "homebridge-simplisafe3.SimpliSafe 3",
    "name": "Home Alarm"
}

which led to these errors:

[12/7/2022, 10:55:07 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 4683
[12/7/2022, 10:55:07 PM] Loaded config.json with 3 accessories and 4 platforms.
[12/7/2022, 10:55:07 PM] Loaded 0 cached accessories from cachedAccessories.
[12/7/2022, 10:55:07 PM] ---
[12/7/2022, 10:55:08 PM] Loaded plugin: homebridge-broadlink-rm-pro@4.4.11
[12/7/2022, 10:55:08 PM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[12/7/2022, 10:55:08 PM] ---
[12/7/2022, 10:55:08 PM] Loaded plugin: homebridge-config-ui-x@4.50.2
[12/7/2022, 10:55:08 PM] Registering platform 'homebridge-config-ui-x.config'
[12/7/2022, 10:55:08 PM] ---
[12/7/2022, 10:55:08 PM] Loaded plugin: homebridge-dummy@0.8.0
[12/7/2022, 10:55:08 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/7/2022, 10:55:08 PM] ---
[12/7/2022, 10:55:08 PM] Loaded plugin: homebridge-nest@4.6.9
[12/7/2022, 10:55:08 PM] Registering platform 'homebridge-nest.Nest'
[12/7/2022, 10:55:08 PM] ---
[12/7/2022, 10:55:08 PM] Loaded plugin: homebridge-simplisafe3@1.10.11
[12/7/2022, 10:55:08 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
[12/7/2022, 10:55:08 PM] ---
[12/7/2022, 10:55:08 PM] Loading 4 platforms...
[12/7/2022, 10:55:08 PM] [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[12/7/2022, 10:55:08 PM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SimpliSafe3AuthenticationManager.parseAccountsFile (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:123:28)
    at new SimpliSafe3AuthenticationManager (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:84:10)
    at new SS3Platform (/usr/local/lib/node_modules/homebridge-simplisafe3/index.js:68:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
[12/7/2022, 10:55:08 PM] Got SIGTERM, shutting down Homebridge...
[12/7/2022, 10:55:08 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[12/7/2022, 10:55:13 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/7/2022, 10:55:18 PM] [HB Supervisor] Restarting Homebridge...
[12/7/2022, 10:55:18 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/7/2022, 10:55:19 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 4693
[12/7/2022, 10:55:19 PM] Loaded config.json with 3 accessories and 4 platforms.
[12/7/2022, 10:55:19 PM] Loaded 0 cached accessories from cachedAccessories.
[12/7/2022, 10:55:19 PM] ---
[12/7/2022, 10:55:20 PM] Loaded plugin: homebridge-broadlink-rm-pro@4.4.11
[12/7/2022, 10:55:20 PM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[12/7/2022, 10:55:20 PM] ---
[12/7/2022, 10:55:20 PM] Loaded plugin: homebridge-config-ui-x@4.50.2
[12/7/2022, 10:55:20 PM] Registering platform 'homebridge-config-ui-x.config'
[12/7/2022, 10:55:20 PM] ---
[12/7/2022, 10:55:20 PM] Loaded plugin: homebridge-dummy@0.8.0
[12/7/2022, 10:55:20 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/7/2022, 10:55:20 PM] ---
[12/7/2022, 10:55:20 PM] Loaded plugin: homebridge-nest@4.6.9
[12/7/2022, 10:55:20 PM] Registering platform 'homebridge-nest.Nest'
[12/7/2022, 10:55:20 PM] ---
[12/7/2022, 10:55:20 PM] Loaded plugin: homebridge-simplisafe3@1.10.11
[12/7/2022, 10:55:20 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
[12/7/2022, 10:55:20 PM] ---
[12/7/2022, 10:55:20 PM] Loading 4 platforms...
[12/7/2022, 10:55:20 PM] [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[12/7/2022, 10:55:20 PM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SimpliSafe3AuthenticationManager.parseAccountsFile (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:123:28)
    at new SimpliSafe3AuthenticationManager (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:84:10)
    at new SS3Platform (/usr/local/lib/node_modules/homebridge-simplisafe3/index.js:68:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
[12/7/2022, 10:55:20 PM] Got SIGTERM, shutting down Homebridge...
[12/7/2022, 10:55:20 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[12/7/2022, 10:55:25 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/7/2022, 10:55:30 PM] [HB Supervisor] Restarting Homebridge...
[12/7/2022, 10:55:30 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/7/2022, 10:55:30 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 4704
[12/7/2022, 10:55:30 PM] Loaded config.json with 3 accessories and 4 platforms.
[12/7/2022, 10:55:30 PM] Loaded 0 cached accessories from cachedAccessories.
[12/7/2022, 10:55:31 PM] ---
[12/7/2022, 10:55:31 PM] Loaded plugin: homebridge-broadlink-rm-pro@4.4.11
[12/7/2022, 10:55:31 PM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[12/7/2022, 10:55:31 PM] ---
[12/7/2022, 10:55:31 PM] Loaded plugin: homebridge-config-ui-x@4.50.2
[12/7/2022, 10:55:31 PM] Registering platform 'homebridge-config-ui-x.config'
[12/7/2022, 10:55:31 PM] ---
[12/7/2022, 10:55:31 PM] Loaded plugin: homebridge-dummy@0.8.0
[12/7/2022, 10:55:31 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/7/2022, 10:55:31 PM] ---
[12/7/2022, 10:55:32 PM] Loaded plugin: homebridge-nest@4.6.9
[12/7/2022, 10:55:32 PM] Registering platform 'homebridge-nest.Nest'
[12/7/2022, 10:55:32 PM] ---
[12/7/2022, 10:55:32 PM] Loaded plugin: homebridge-simplisafe3@1.10.11
[12/7/2022, 10:55:32 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
[12/7/2022, 10:55:32 PM] ---
[12/7/2022, 10:55:32 PM] Loading 4 platforms...
[12/7/2022, 10:55:32 PM] [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[12/7/2022, 10:55:32 PM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SimpliSafe3AuthenticationManager.parseAccountsFile (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:123:28)
    at new SimpliSafe3AuthenticationManager (/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js:84:10)
    at new SS3Platform (/usr/local/lib/node_modules/homebridge-simplisafe3/index.js:68:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
[12/7/2022, 10:55:32 PM] Got SIGTERM, shutting down Homebridge...
[12/7/2022, 10:55:32 PM] [Homebridge UI] Changes to config.json saved.
[12/7/2022, 10:55:32 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[12/7/2022, 10:55:37 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/7/2022, 10:55:42 PM] [HB Supervisor] Restarting Homebridge...
[12/7/2022, 10:55:42 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/7/2022, 10:55:42 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 4714
[12/7/2022, 10:55:42 PM] Loaded config.json with 3 accessories and 4 platforms.
[12/7/2022, 10:55:42 PM] Loaded 0 cached accessories from cachedAccessories.
[12/7/2022, 10:55:42 PM] ---
[12/7/2022, 10:55:43 PM] Loaded plugin: homebridge-broadlink-rm-pro@4.4.11
[12/7/2022, 10:55:43 PM] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[12/7/2022, 10:55:43 PM] ---
[12/7/2022, 10:55:43 PM] Loaded plugin: homebridge-config-ui-x@4.50.2
[12/7/2022, 10:55:43 PM] Registering platform 'homebridge-config-ui-x.config'
[12/7/2022, 10:55:43 PM] ---
[12/7/2022, 10:55:43 PM] Loaded plugin: homebridge-dummy@0.8.0
[12/7/2022, 10:55:43 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/7/2022, 10:55:43 PM] ---
[12/7/2022, 10:55:43 PM] Loaded plugin: homebridge-nest@4.6.9
[12/7/2022, 10:55:43 PM] Registering platform 'homebridge-nest.Nest'
[12/7/2022, 10:55:43 PM] ---
[12/7/2022, 10:55:43 PM] Disabled plugin: homebridge-simplisafe3@1.10.11
[12/7/2022, 10:55:43 PM] ---
[12/7/2022, 10:55:43 PM] Loading 4 platforms...
[12/7/2022, 10:55:43 PM] Ignoring config for the platform "homebridge-simplisafe3.SimpliSafe 3" in your config.json as the plugin "homebridge-simplisafe3" has been disabled.
```

### Plugin version

└── homebridge-simplisafe3@1.10.11

### Homebridge version

1.6.0

### Node.js version

v16.16.0

### Host OS

macOS

**Comment by cattastrophe0** [comment]
https://user-images.githubusercontent.com/57551805/206383082-22e3df5e-5dff-42d6-a462-86e1c5f64057.mov

screen recording of UI setup issue

**Comment by shamoon** [comment]
Looks like your auth file got messed up, delete it from inside your homebridge storage path, usually either `~/.homebridge/simplisafe3auth.json` or `/var/lib/homebridge/simplisafe3auth.json` but it will say on the homebridge startup page

**Comment by cattastrophe0** [comment]
That was it, thank you! Is there a way to tell that file was the issue from the logs? I got thrown off by `/usr/local/lib/node_modules/homebridge-simplisafe3/lib/authManager.js` repeatedly showing up.
