### ISSUE TITLE
Unable to login again

### ISSUE THREAD

**Issue by boakham** [homebridge-simplisafe3/homebridge-simplisafe3#391]
### Description

Have SimpliSafe broken the login process again? I had to reboot my homebridge yesterday and now I can't login to the SimpliSafe plugin. Using the process, Homebridge just says there was an error retrieving the token.

### Expected behavior

Authenticate with SimpliSafe

### Steps to reproduce

Follow standard authentication process

### Homebridge logs

```bash
[5/27/2023, 8:40:59 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 36A3) is running on port 51949.
[5/27/2023, 8:41:08 AM] [Homebridge UI] [homebridge-simplisafe3] Failed to check registry.npmjs.org for updates: "getaddrinfo EAI_AGAIN registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.
[5/27/2023, 8:41:08 AM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "getaddrinfo EAI_AGAIN registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.
[5/27/2023, 8:41:10 AM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /credentialsExist
[5/27/2023, 8:41:10 AM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getCodeVerifier
[5/27/2023, 8:41:10 AM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getSSAuthURL
[5/27/2023, 8:42:16 AM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getAuthCodeFromUrl
[5/27/2023, 8:42:16 AM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getToken
[5/27/2023, 8:42:16 AM] [Homebridge UI] [homebridge-simplisafe3] Error: getaddrinfo EAI_AGAIN auth.simplisafe.com
    at SimpliSafe3AuthenticationManager.getToken (/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:183:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UiServer.getToken (/homebridge/node_modules/homebridge-simplisafe3/homebridge-ui/server.js:65:12)
    at async UiServer.processRequest (/homebridge/node_modules/homebridge-simplisafe3/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
```

### Homebridge config.json contents

```json
{
    "name": "Simplisafe",
    "cameras": true,
    "debug": true,
    "sensorRefresh": 3,
    "persistAccessories": true,
    "cameraOptions": {
        "enableHwaccelRpi": false
    },
    "excludedDevices": [
        "03f0a8f",
        "f1079f4a"
    ],
    "platform": "homebridge-simplisafe3.SimpliSafe 3"
}
```

### Plugin version

1.10.13

### Homebridge version

1.6.0

### Node.js version

18.13.0

### Host OS

Docker

**Comment by shamoon** [comment]
`Error: getaddrinfo EAI_AGAIN auth.simplisafe.com` means your instance cant reach the internet for some reason.

Dont think login is broken.

**Comment by boakham** [comment]
Oh you're right, thank you! I didn't notice that.
