### ISSUE TITLE
[BUG] Authentication JSON File Clears After Bad Pull Frequently

### ISSUE THREAD

**Issue by kobys8** [homebridge-simplisafe3/homebridge-simplisafe3#400]
### Description

Whenever I reauthenticate my Simplisafe using the instructions provided for Homebridge, the login works for 1-2 weeks before it crashes my Homebridge due to the dreaded "Unexpected End of JSON input" error for the authentication file. After deleting the file a couple times and reauthenticating, I investigated the JSON file itself and found that the file was completely empty, making me think that when the service attempted to reach Simplisafe to update a token, it received a null response and put that in the authentication file.

### Expected behavior

The authentication for Simplisafe remains for an extended period of time.

### Steps to reproduce

1. Authenticate with Simplisafe using the "com.simplisafe...." method.
2. Wait about two weeks
3. Homebridge will crash, saying the JSON file couldn't be parsed.

### Homebridge logs

```bash
bridge/node_modules/homebridge-simplisafe3/lib/authManager.js:128:28)[39m
[31m    at new SimpliSafe3AuthenticationManager (/var/lib/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:87:10)[39m
[31m    at new SS3Platform (/var/lib/homebridge/node_modules/homebridge-simplisafe3/index.js:68:24)[39m
[31m    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:474:40[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server.loadPlatforms (/var/lib/homebridge/node_modules/homebridge/src/server.ts:401:27)[39m
[31m    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:29)[39m
[37m[8/27/2023, 9:19:11 AM] [39mGot SIGTERM, shutting down Homebridge...
[37m[8/27/2023, 9:19:11 AM] [39m[31mAssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet![39m
[31m    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)[39m
[31m    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)[39m
[31m    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)[39m
[31m    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)[39m
[31m    at process.emit (node:events:514:28)[39m
[31m    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)[39m
[37m[8/27/2023, 9:19:16 AM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[8/27/2023, 9:19:21 AM][0m [36m[HB Supervisor][0m Restarting Homebridge...
[37m[8/27/2023, 9:19:21 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[37m[8/27/2023, 9:19:21 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.6.1 with PID: 3962466
[37m[8/27/2023, 9:19:21 AM] [39mLoaded config.json with 0 accessories and 4 platforms.
[37m[8/27/2023, 9:19:21 AM] [39mLoaded 17 cached accessories from cachedAccessories.
[37m[8/27/2023, 9:19:21 AM] [39m---
[37m[8/27/2023, 9:19:21 AM] [39mLoaded plugin: homebridge-nest@4.6.9
[37m[8/27/2023, 9:19:21 AM] [39mRegistering platform 'homebridge-nest.Nest'
[37m[8/27/2023, 9:19:21 AM] [39m---
[37m[8/27/2023, 9:19:21 AM] [39mLoaded plugin: homebridge-nest-cam@7.5.4
[37m[8/27/2023, 9:19:21 AM] [39mRegistering platform 'homebridge-nest-cam.Nest-cam'
[37m[8/27/2023, 9:19:21 AM] [39m---
[37m[8/27/2023, 9:19:22 AM] [39mLoaded plugin: homebridge-simplisafe3@1.10.13
[37m[8/27/2023, 9:19:22 AM] [39mRegistering platform 'homebridge-simplisafe3.SimpliSafe 3'
[37m[8/27/2023, 9:19:22 AM] [39m---
[37m[8/27/2023, 9:19:22 AM] [39mLoading 4 platforms...
[37m[8/27/2023, 9:19:22 AM] [39m[36m[Nest][39m Initializing Nest platform...
[37m[8/27/2023, 9:19:22 AM] [39m[36m[Nest-cam][39m Initializing Nest-cam platform...
[37m[8/27/2023, 9:19:22 AM] [39m[36m[Nest-cam][39m Initializing child bridge 0E:1A:51:11:CB:98
[37m[8/27/2023, 9:19:22 AM] [39m[36m[Home Alarm][39m Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[37m[8/27/2023, 9:19:22 AM] [39m[31mSyntaxError: Unexpected end of JSON input[39m
[31m    at JSON.parse (<anonymous>)[39m
[31m    at SimpliSafe3AuthenticationManager.parseAccountsFile (/var/lib/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:128:28)[39m
[31m    at new SimpliSafe3AuthenticationManager (/var/lib/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:87:10)[39m
[31m    at new SS3Platform (/var/lib/homebridge/node_modules/homebridge-simplisafe3/index.js:68:24)[39m
[31m    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:474:40[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server.loadPlatforms (/var/lib/homebridge/node_modules/homebridge/src/server.ts:401:27)[39m
[31m    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:29)[39m
[37m[8/27/2023, 9:19:22 AM] [39mGot SIGTERM, shutting down Homebridge...
[37m[8/27/2023, 9:19:22 AM] [39m[31mAssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet![39m
[31m    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)[39m
[31m    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)[39m
[31m    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)[39m
[31m    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)[39m
[31m    at process.emit (node:events:514:28)[39m
[31m    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)[39m
[37m[8/27/2023, 9:19:27 AM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[8/27/2023, 9:19:32 AM][0m [36m[HB Supervisor][0m Restarting Homebridge...
[37m[8/27/2023, 9:19:32 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[37m[8/27/2023, 9:19:32 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.6.1 with PID: 3962520
[37m[8/27/2023, 9:19:32 AM] [39mLoaded config.json with 0 accessories and 4 platforms.
[37m[8/27/2023, 9:19:32 AM] [39mLoaded 17 cached accessories from cachedAccessories.
[37m[8/27/2023, 9:19:32 AM] [39m---
[37m[8/27/2023, 9:19:32 AM] [39mLoaded plugin: homebridge-nest@4.6.9
[37m[8/27/2023, 9:19:32 AM] [39mRegistering platform 'homebridge-nest.Nest'
[37m[8/27/2023, 9:19:32 AM] [39m---
[37m[8/27/2023, 9:19:32 AM] [39mLoaded plugin: homebridge-nest-cam@7.5.4
[37m[8/27/2023, 9:19:32 AM] [39mRegistering platform 'homebridge-nest-cam.Nest-cam'
[37m[8/27/2023, 9:19:32 AM] [39m---
[37m[8/27/2023, 9:19:32 AM] [39mLoaded plugin: homebridge-simplisafe3@1.10.13
[37m[8/27/2023, 9:19:32 AM] [39mRegistering platform 'homebridge-simplisafe3.SimpliSafe 3'
[37m[8/27/2023, 9:19:32 AM] [39m---
[37m[8/27/2023, 9:19:32 AM] [39mLoading 4 platforms...
[37m[8/27/2023, 9:19:32 AM] [39m[36m[Nest][39m Initializing Nest platform...
[37m[8/27/2023, 9:19:32 AM] [39m[36m[Nest-cam][39m Initializing Nest-cam platform...
[37m[8/27/2023, 9:19:32 AM] [39m[36m[Nest-cam][39m Initializing child bridge 0E:1A:51:11:CB:98
[37m[8/27/2023, 9:19:32 AM] [39m[36m[Home Alarm][39m Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[37m[8/27/2023, 9:19:32 AM] [39m[31mSyntaxError: Unexpected end of JSON input[39m
[31m    at JSON.parse (<anonymous>)[39m
[31m    at SimpliSafe3AuthenticationManager.parseAccountsFile (/var/lib/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:128:28)[39m
[31m    at new SimpliSafe3AuthenticationManager (/var/lib/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:87:10)[39m
[31m    at new SS3Platform (/var/lib/homebridge/node_modules/homebridge-simplisafe3/index.js:68:24)[39m
[31m    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:474:40[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server.loadPlatforms (/var/lib/homebridge/node_modules/homebridge/src/server.ts:401:27)[39m
[31m    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:29)[39m
[37m[8/27/2023, 9:19:32 AM] [39mGot SIGTERM, shutting down Homebridge...
[37m[8/27/2023, 9:19:32 AM] [39m[31mAssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet![39m
[31m    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)[39m
[31m    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)[39m
[31m    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)[39m
[31m    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)[39m
[31m    at process.emit (node:events:514:28)[39m
[31m    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)[39m
[37m[8/27/2023, 9:19:37 AM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[8/27/2023, 9:19:42 AM][0m [36m[HB Supervisor][0m Restarting Homebridge...
```

### Homebridge config.json contents

```json
{
    "bridge": {
        "name": "Homebridge E985",
        "username": "USERNAME",
        "port": PORT,
        "pin": "PIN",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "ISSUE_TOKEN",
                "cookies": "COOKIE"
            },
            "options": [
                "HomeAway.Disable"
            ],
            "platform": "Nest"
        },
        {
            "platform": "Nest-cam",
            "options": {
                "ffmpegCodec": "libx264",
                "motionDetection": true,
                "streamingSwitch": true,
                "disableAudio": false,
                "streamQuality": 3,
                "doorbellAlerts": true,
                "doorbellSwitch": false
            },
            "googleAuth": {
                "issueToken": "ISSUE_TOKEN",
                "cookies": "COOKIE"
            },
            "_bridge": {
                "username": "USERNAME",
                "port": PORT_NUM
            }
        },
        {
            "name": "Home Alarm",
            "cameras": true,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": true
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
    ],
    "disabledPlugins": []
}
```

### Plugin version

1.10.13

### Homebridge version

1.6.1

### Node.js version

18.17.1

### Host OS

Debian

**Comment by shamoon** [comment]
In almost 3 years of maintaining and using the plug-in I have never seen this (myself or reported). Aka I cant reproduce it

**Comment by kobys8** [comment]
That's fair! I still am going to try to use this plugin but thought it wouldn't hurt to bring up just in case.

**Comment by shamoon** [comment]
If you are able to provide logs from when the issue actually starts that could be helpful

**Comment by kobys8** [comment]
I will reauthenticate and keep a close eye on when it errors and grab logs as soon as I see it happen again.On Aug 27, 2023, at 13:38, shamoon ***@***.***> wrote:﻿
If you are able to provide logs from when the issue actually starts that could be helpful

**Comment by shamoon** [comment]
Yea just reviewing the code i don’t see why SS would return a null response for this and even if it did it shouldn’t write a completely empty file, see 

https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/blob/master/src/lib/authManager.js#L186

Yea keep me posted on what you find

**Comment by shamoon** [comment]
Also one other thought is something with file perms or even corruption
