### ISSUE TITLE
Authorization url not working 

### ISSUE THREAD

**Issue by Brian8731** [homebridge-simplisafe3/homebridge-simplisafe3#446]
### Description

I get to the point of logging into SimpliSafe and get a txt auth to log in  and that works then it goes to error screen the url starts with auth

### Expected behavior

I should be getting past the pop up with a auth url

### Steps to reproduce

1 go to SimpliSafe plugin and click authentication link I go through the process then it pops up cannot open the page because the address is invalid. I’ve tried this on MacBook and windows same results and the only address I see begins with auth.SimpliSafe.com

### Homebridge logs

```bash
57:41 PMSimplisafe3 BridgeinfoLoaded plugin 'homebridge-simplisafe3'
12:57:41 PMSimplisafe3 BridgeinfoLoading 1 platforms...
12:57:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3errorSimpliSafe login failed with error: Error: No valid authentication credentials detected. at SimpliSafe3AuthenticationManager.refreshCredentials (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/lib/authManager.js:189:13) at new SS3Platform (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:82:41) at /usr/src/bridge/server.ts:508:46 at Array.forEach (<anonymous>) at Server.loadPlatforms (/usr/src/bridge/server.ts:491:31) at Server.start (/usr/src/bridge/server.ts:285:69) at processTicksAndRejections (node:internal/process/task_queues:95:5)
12:57:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3errorSee the plugin README for more information on authenticating with SimpliSafe.
12:57:41 PMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3errorInitial accessories refresh failed with error: Error: Not authenticated with SimpliSafe. at /var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:101:56 at processTicksAndRejections (node:internal/process/task_queues:95:5)
12:57:41 PMSimplisafe3 BridgeinfoBridge is running on port 51936.
12:57:50 PMHubinfo[homebridge-simplisafe3] Child process 24829 started
12:57:50 PMHubinfoMessage received {"action":"ready","payload":{"server":true}}
12:57:51 PMHubinfo[homebridge-simplisafe3] request received [{"action":"request","path":"/credentialsExist","requestId":"w8w778jnj0m"}]
12:57:51 PMHubinfo[homebridge-simplisafe3] sending data to child...
12:57:51 PMHubinfoMessage received {"action":"response","payload":{"requestId":"w8w778jnj0m","success":true,"data":{"success":true,"credentialsExist":false}}}
12:57:51 PMHubinfo[homebridge-simplisafe3] request received [{"action":"request","path":"/getCodeVerifier","requestId":"or7sigqfyi"}]
12:57:51 PMHubinfo[homebridge-simplisafe3] sending data to child...
12:57:51 PMHubinfoMessage received {"action":"response","payload":{"requestId":"or7sigqfyi","success":true,"data":{"success":true,"codeVerifier":"o9LzSk2-_l2vCEK7b26NcgLftyVOd-LPNml-TwqUSCY"}}}
12:57:51 PMHubinfo[homebridge-simplisafe3] request received [{"action":"request","path":"/getSSAuthURL","requestId":"suuieig58q"}]
12:57:51 PMHubinfo[homebridge-simplisafe3] sending data to child...
12:57:51 PMHubinfoMessage received {"action":"response","payload":{"requestId":"suuieig58q","success":true,"data":{"success":true,"url":"https://auth.simplisafe.com/authorize?client_id=42aBZ5lYrVW12jfOuu3CQROitwxg9sN5&scope=offline_access%20email%20openid%20https://api.simplisafe.com/scopes/user:platform&response_type=code&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&code_challenge_method=S256&code_challenge=c6YkcPB1fczifDbbARM9nmz1LQt02Nscz-pMVJpiQB8&audience=https://api.simplisafe.com/&auth0Client=eyJ2ZXJzaW9uIjoiMi4zLjIiLCJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsic3dpZnQiOiI1LngiLCJpT1MiOiIxNi4zIn19&device=iPhone&device_id=0000007E-0000-1000-8000-0026BB765291"}}}
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:58:12 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:32 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
12:59:55 PMHubinfo[homebridge-simplisafe3] disconnecting 24829
```

### Homebridge config.json contents

```json
{
    "name": "Home Alarm",
    "cameras": false,
    "debug": true,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "cameraOptions": {
        "enableHwaccelRpi": false
    }
}
```

### Screenshots

![IMG_1687](https://github.com/user-attachments/assets/02b86653-688f-4d82-af50-4240c2ef9916) 
I know this is on mobile but the message is the same on Mac or pc

### Plugin version

1.10.13

### Homebridge version

Hoobs

### Node.js version

?

### Host OS

Raspbian

**Comment by shamoon** [comment]
Please read the docs more carefully and you can search here. You cannot do this on mobile and use chrome. I don’t think this is suddenly broken, although that may happen some day, today is not that day

**Comment by Brian8731** [comment]
I use MacBook and pc not working
Sent from my iPhone

On Dec 23, 2024, at 3:38 PM, shamoon ***@***.***> wrote:

﻿

Please read the docs more carefully and you can search here. You cannot do this on mobile and use chrome. I don’t think this is suddenly broken, although that may happen some day, today is not that day

**Comment by Brian8731** [comment]
I used MacBook and pc with no luck

**Comment by brainstorm-tech** [comment]
Hi Brian,

 

Are you using F12 and your browser to pick out the auth key, and paste it into the appropriate spot in the HomeKit plugin?

 

I found that I had to clear the cookies in my Chromium browser, then do the authentication, then use F12 and it would show me the auth key.  If I didn’t clear out the cookies, it didn’t work.

 

(MacBook user here)

-Ed

 

From: Brian8731 ***@***.***>
Reply-To: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>
Date: Monday, December 23, 2024 at 2:41 PM
To: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [homebridge-simplisafe3/homebridge-simplisafe3] Authorization url not working (Issue #446)

 

I used MacBook and pc with no luck

**Comment by shamoon** [comment]
Honestly, read it carefully: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3?tab=readme-ov-file#simplisafe-authentication

You cannot use all browsers and need to find the url in the browser console

**Comment by shamoon** [comment]
E.g. https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/359#discussioncomment-3389753

**Comment by Brian8731** [comment]
![IMG_1689](https://github.com/user-attachments/assets/f2f1e7fd-3498-4615-8832-f6539ba62555)
Hangs here

**Comment by Brian8731** [comment]
Everything is working now didn’t know what error console was thanks
Sent from my iPhone

On Dec 23, 2024, at 4:46 PM, shamoon ***@***.***> wrote:

﻿

E.g. #359 (comment)<https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/359#discussioncomment-3389753>
